### ISSUE TITLE
BUGs ;)

### ISSUE THREAD

**Issue by GeoSn0w** [jakeajames/yalu102-space#3]
I can write in the text box you've used to describe what increasing vnodes does.
Also, that window has absolutely no way to close it, one must close the app to quit that window once open.

**Comment by jakeajames** [comment]
@GeoSn0w Didn't notice the first actually... 
Hmm. I can close it on an iPad by just clicking outside. I think I have to test on an iPhone

**Comment by jakeajames** [comment]
Fixed all of them :)

**Comment by GeoSn0w** [comment]
You also have one that gets "Jailbreaking...." stuck even after the Jailbreak is done.

**Comment by jakeajames** [comment]
@GeoSn0w Close the app and it will show "Successfuly jailbroken". Apparently I need to make it change after the jailbreak is done too (not only in viewDidLoad)

**Comment by jakeajames** [comment]
@GeoSn0w Should be challenging since the jailbreak starts at ViewController.m and ends at jailbreak.m. I would need to find a way to modify the jailbreak button image, which is linked to ViewController.m, via jailbreak.m

**Comment by GeoSn0w** [comment]
Not really, you can do it differently, I'll push a pull request if you want.

**Comment by jakeajames** [comment]
@GeoSn0w Nvm I think I can do it
